---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nextjs
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/insuusvenerati/nextjs-k8s
